[build]
  base = "frontend"
  command = "CI=false npm run build && ./post-build.sh"
  publish = "build"

# Service Worker - must not be redirected
[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200

# Manifest - must not be redirected
[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200

# SPA redirect for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# PWA Headers
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Service-Worker-Allowed = "/"
    Content-Type = "application/javascript"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/splash/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Security Headers for PWA
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(self), camera=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob:; connect-src 'self' https:; media-src 'self' blob:; worker-src 'self' blob:;"
