[build]
  base = "frontend"
  command = "CI=false npm run build:pwa"
  publish = "build"

# Service Worker - must not be redirected
[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200

# SPA redirect for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# PWA Headers
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Service-Worker-Allowed = "/"
    Content-Type = "application/javascript"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/splash/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Security Headers for PWA
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(self), camera=()"
